import Head from 'next/head'
import ContactForm from '../components/ContactForm'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Next.js!
        </h1>
      </main>
      <ContactForm />
    </div>
  )
}
